name: Localization Push

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - localization/**/*.json

jobs:
  sync_localizations:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Push JSON to Google Sheets
        uses: ./  # Use the local action
        with:
          action: push
          google_api_key_json: ${{ secrets.GOOGLE_API_KEY_JSON }}
          spreadsheet_id: ${{ vars.SPREADSHEET_ID }}
          localization_root: ./localization
